name: opencv-rust
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  workflow_dispatch:
permissions:
  contents: read
jobs:
  vcpkg:
    strategy:
      fail-fast: false
      matrix:
        os-image:
          - ubuntu-24.04
          - ubuntu-22.04
          - windows-2022
          - windows-2025
          - macos-14
          - macos-15
        vcpkg-version:
          - 2025.04.09 # https://github.com/microsoft/vcpkg/releases
        vcpkg-features-cache-key:
          - full
        vcpkg-features:
          - jpeg,tiff,world
    runs-on: ${{ matrix.os-image }}
    env:
      VCPKG_VERSION: ${{ matrix.vcpkg-version }}
      VCPKG_FEATURES: ${{ matrix.vcpkg-features }}
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: mozilla-actions/sccache-action@v0.0.9
      - uses: actions/cache@v4
        with:
          path: ~/build
          key: vcpkg-${{ matrix.vcpkg-version }}-${{ matrix.os-image }}-${{ matrix.vcpkg-features-cache-key }}

      - name: Install dependencies
        run: ci/install.sh
        shell: bash

      - name: Test project
        run: ci/script.sh
        shell: bash
